---
format: 
  gfm: default
editor: source
---

# Title

Open Science Tools - authoring and publishing workflows for collaborative scientific writing

# Catalogue Data

## Abstract

Researchers are facing increasing expectations, including the need to provide data management plans for proposals, share data underlying publications, and ensure research results can be reproduced. However, it can be challenging to determine which tools to use to meet these expectations.

This course aims to help researchers navigate these challenges by introducing a workflow that utilizes Git version control, GitHub, and the Quarto scientific and technical publishing system for collaborative scientific writing.

During the course, participants will learn how to use the Quarto file format to prepare various scholarly documents, including slides, scientific articles, books, and websites. Additionally, we will demonstrate how GitHub can serve as both a project management tool and a publishing platform using GitHub Pages.

## Objective

This course has the following learning objectives

1. Learn to use the Quarto file format and the RStudio IDE visual editing mode to produce scholarly documents with citations, footnotes, cross-references, figures, and tables.

2. Explain the differences between files written in markup languages like markdown (.md) and those in proprietary file formats like .docx.

3. Utilize an exported library from Zotero in Better BibTex Format to create an automated reference list in your scientific documents.

4. Interact with Git version control and GitHub through the RStudio IDE.

5. Collaborate with other researchers using the GitHub issue tracker and project management board to organize tasks and streamline communication.

6. Publish a public website using GitHub Pages to share research with a broader audience.

## Content

This course offers researchers a hands-on opportunity to learn open source tools and platforms that are accessible beyond institutional employment. The participatory live coding teaching technique involves an instructor writing and narrating code as they teach, and inviting learners to write and execute the same code.

Topics covered include scientific communication, reproducible research (open research, version control, licensing), and collaboration through Git and GitHub.

While the course will introduce commonly used tools in software development, they will not be explained in great detail. Instead, the goal is to expose learners to the tools and concepts, requiring openness to new ideas.

Overall, this course provides a practical approach for researchers to learn important tools for scientific communication, reproducibility, and collaboration.

## Lecture notes

A public website is in preparation.

## Prerequisites / Notice

Prior experience in a programming language is not required for this course, but learners who have worked with data science tools such as R, RStudio IDE, Jupyter Notebooks, Python, or VS Code may have an advantage and gain the most from the material.

Prior to the course, learners are expected to have:

-   a laptop with internet connection and one of Mozilla Firefox, Safari, Google Chrome, Microsoft Edge (just not the Internet Explorer)
-   a registered account on GitHub (https://github.com/)
-   a registered ORCID iD (https://orcid.org/)
-   read the following paper: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510

Two weeks before the course begins, the instructor will contact registered participants to provide a reminder about the prerequisites.

# Performance Assessment

Successful participation in this course earns participants 0.5 ECTS, equivalent to 15 working hours. The course consists of two 4-hour modules, with the remaining 7 hours designated for participant preparation before the first module and between the two modules.